# Generated by Django 4.1.1 on 2022-10-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='harga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='stok',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
